from googletrans import LANGCODES, LANGUAGES

G2P_LANGUAGES = {
    "Adyghe": "ady",
    "Afrikaans": "afr",
    "Albanian": "sqi",
    "Amharic": "amh",
    "Arabic": "ara",
    "Aragonese": "arg",
    "East Armenian": "arm-e",
    "West Armenian": "arm-w",
    "Azerbaijani": "aze",
    "Bashkir": "bak",
    "Basque": "eus",
    "Belarussian": "bel",
    "Bengali": "ben",
    "Bosnian": "bos",
    "Bulgarian": "bul",
    "Burmese": "bur",
    "Catalan": "cat",
    "Cantonese": "yue",
    "Mandarin (traditional)": "zho-t",
    "Mandarin (simplified)": "zho-s",
    "Min Nan": "min",
    "Czech": "cze",
    "Danish": "dan",
    "Dutch": "dut",
    "British English": "eng-uk",
    "American English": "eng-us",
    "Esperanto": "epo",
    "Estonian": "est",
    "Finnish": "fin",
    "French": "fra",
    "French (Quebec)": "fra-qu",
    "Gaelic": "gla",
    "Georgian": "geo",
    "German": "ger",
    "Greek": "gre",
    "Ancient Greek": "grc",
    "Guarani": "grn",
    "Gujarati": "guj",
    "Hindi": "hin",
    "Hungarian": "hun",
    "Ido": "ido",
    "Indonesian": "ind",
    "Interlingua": "ina",
    "Italian": "ita",
    "Jamaican Creole": "jam",
    "Japanese": "jpn",
    "Kazakh": "kaz",
    "Khmer": "khm",
    "Korean": "kor",
    "Kurdish": "kur",
    "Latin Classical": "lat-clas",
    "Latin Ecclesiastical": "lat-eccl",
    "Lithuanian": "lit",
    "Luxembourgish": "ltz",
    "Macedonian": "mac",
    "Maltese": "mlt",
    "Noethestern Thai": "tts",
    "Norwegian Bokm?l": "nob",
    "Oriya": "ori",
    "Papiamento": "pap",
    "Persian": "fas",
    "Polish": "pol",
    "Portuguese (Brazil)": "por-br",
    "Portuguese (Portugal)": "por-po",
    "Romanian": "ron",
    "Russian": "rus",
    "Sanskrit": "san",
    "Serbian": "srp",
    "Serbian (Latin)": "hbs-latn",
    "Serbian (Cyrillic)": "hbs-cyrl",
    "Sindhi": "snd",
    "Slovak": "slo",
    "Slovenian": "slv",
    "Spanish (Latin America)": "spa-latin",
    "Spanish (Mexico)": "spa-me",
    "Spanish": "spa",
    "Swahili": "swa",
    "Swedish": "swe",
    "Tagalog": "tgl",
    "Tamil": "tam",
    "Tatar": "tat",
    "Thai": "tha",
    "Turkish": "tur",
    "Turkmen": "tuk",
    "Ukrainian": "ukr",
    "Vietnamese (Northern)": "vie-n",
    "Vietnamese (Central)": "vie-c",
    "Vietnamese (Southern)": "vie-s",
    "Welsh (North)": "wel-nw",
    "Welsh (South)": "wel-sw",
    "Icelandic": "ice",
    "Old English": "ang",
    "Irish": "gle",
    "Middle English": "enm",
    "Classical Syriac": "syc",
    "Galician": "glg",
    "Northern Sami": "sme",
    "Egyptian": "egy",
}
G2P_LANGCODES = dict(map(reversed, G2P_LANGUAGES.items()))

# Google Translate
TRANSLATE_LANGUAGES = LANGUAGES
TRANSLATE_LANGCODES = LANGCODES

# Vocab Languages
VOCAB_LANGUAGES = [
    "af",
    "ar",
    "bg",
    "bn",
    "br",
    "bs",
    "ca",
    "cs",
    "da",
    "de",
    "el",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fr",
    "gl",
    "he",
    "hi",
    "hr",
    "hu",
    "hy",
    "id",
    "is",
    "it",
    "ja",
    "ka",
    "kk",
    "ko",
    "lt",
    "lv",
    "mk",
    "ml",
    "ms",
    "nl",
    "no",
    "pl",
    "pt",
    "pt_br",  # Brazilian Portuguese
    "ro",
    "ru",
    "si",
    "sk",
    "sl",
    "sq",
    "sr",
    "sv",
    "ta",
    "te",
    "th",
    "tl",
    "tr",
    "uk",
    "ur",
    "vi",
    "ze_en",  # Chinese & English
    "ze_zh",  # Chinese & English
    "zh_cn",  # Simplified Chinese
    "zh_tw",  # Traditional Chinese
]
