LOGGING_LEVEL: "DEBUG"

# Anki deck name
DECK_NAME: "mnemorai"

# The model to use for grapheme to phoneme conversion (G2P)
G2P:
  MODEL: "charsiu/g2p_multilingual_byT5_small_100"
  TOKENIZER: "google/byt5-small"
  LANGUAGE_JSON: "data/languages.json"

# The model to use for generating the mnemonic and creating the verbal cue
LLM:
  # We recommend the models from unsloth: https://docs.unsloth.ai/get-started/all-our-models
  SMALL_MODEL: "unsloth/Qwen2.5-3B-Instruct-bnb-4bit" # 3GB vram
  MEDIUM_MODEL: "unsloth/Qwen2.5-7B-Instruct-bnb-4bit" # 6GB vram
  LARGE_MODEL: "unsloth/Qwen2.5-14B-Instruct-bnb-4bit" # 9GB vram
  # Options are: None, 4bit, 8bit
  # Use None if you use an unsloth model (these are already quantized)
  QUANTIZATION: None
  USE_LORA: False
  LORA: "StephanAkkerman/Phi-3-mini-4k-instruct-QLoRA-4bit-Mnemonic"
  DELETE_AFTER_USE: False
  OFFLOAD: True
  PARAMS:
    #temperature: 0.5

# The model to use for generating the image
IMAGE_GEN:
  SMALL_MODEL: stabilityai/stable-diffusion-2 # 3GB vram
  MEDIUM_MODEL: stabilityai/sdxl-turbo # 6GB vram
  LARGE_MODEL: Efficient-Large-Model/Sana_600M_512px_diffusers # 9GB vram
  OUTPUT_DIR: "imagine/generated-img"
  # Options are: None, 4bit, 8bit
  QUANTIZATION: None # only supported for Sana at the moment
  DELETE_AFTER_USE: False
  OFFLOAD: True # This must be False if quantization != None
  PARAMS:
    num_inference_steps: 40
    height: 512
    width: 512