[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
profile = "black"

[tool.ruff]
line-length = 88
# https://docs.astral.sh/ruff/rules/
select = [
    # "E",  # pycodestyle (E1xx)
    # "W",  # pycodestyle (W1xx)
    "F",   # flake8 (F4xx)
    "I",   # isort (I001)
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "TCH", # flake8-type-checking (does this work)
]
ignore = ["D100", "D101", "D104", "D200", "D401"]

[tool.ruff.lint.pydocstyle]
# Use numpy-style docstrings.
convention = "numpy"
