[tool.ruff]
src = ["."]
line-length = 88
# https://docs.astral.sh/ruff/rules/

[tool.ruff.lint]
select = [
    # "E",  # pycodestyle (E1xx)
    # "W",  # pycodestyle (W1xx)
    "F",   # flake8 (F4xx)
    "I",   # isort (I001)
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "TCH", # flake8-type-checking (does this work)
]
ignore = ["D100", "D101", "D104", "D200", "D401"]

[tool.ruff.lint.pydocstyle]
# Use numpy-style docstrings.
convention = "numpy"

[tool.ruff.lint.isort]
# https://docs.astral.sh/ruff/settings/#lintisort
known-third-party = ["datasets"]
