name: Run Black formatter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: false
