name: Auto Tag and Assign "In Progress"

on:
  push:
    # Trigger on pushes to any branch
    branches:
      - '**'
  pull_request:
    # Trigger on pull request events
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  tag-and-assign-in-progress:
    runs-on: ubuntu-latest

    env:
      label: "In Progress 🚧"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Auto Tag and Assign Issues with "In Progress"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = process.env.label;

            // Function to add label to an issue
            async function addLabel(owner, repo, issue_number) {
              try {
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number,
                  labels: [label],
                });
                console.log(`Added label "${label}" to issue #${issue_number}`);
              } catch (error) {
                console.error(`Failed to add label to issue #${issue_number}:`, error);
              }
            }

            // Function to assign a user to an issue
            async function assignUser(owner, repo, issue_number, username) {
              try {
                await github.rest.issues.addAssignees({
                  owner,
                  repo,
                  issue_number,
                  assignees: [username],
                });
                console.log(`Assigned @${username} to issue #${issue_number}`);
              } catch (error) {
                console.error(`Failed to assign @${username} to issue #${issue_number}:`, error);
              }
            }

            // Regex to find issue references like #123
            const issueRegex = /(?:^|\s)#(\d+)/g;

            // Set to store unique issue numbers
            const issues = new Set();

            // Set to store unique usernames to assign
            const assignees = new Set();

            if (context.eventName === 'push') {
              const commits = context.payload.commits;
              for (const commit of commits) {
                let message = commit.message;
                let matches;
                while ((matches = issueRegex.exec(message)) !== null) {
                  issues.add(parseInt(matches[1]));
                  console.log(`Found issue reference #${matches[1]} in commit message: ${message}`);
                  // Add commit author as assignee
                  if (commit.author && commit.author.username) {
                    assignees.add(commit.author.username);
                  }
                }
              }
            }

            if (context.eventName === 'pull_request') {
              const pr = context.payload.pull_request;
              const body = pr.body || '';
              let matches;
              while ((matches = issueRegex.exec(body)) !== null) {
                issues.add(parseInt(matches[1]));
                // Add PR author as assignee
                if (pr.user && pr.user.login) {
                  assignees.add(pr.user.login);
                }
              }

              // Additionally, check the PR title for issue references
              const title = pr.title || '';
              while ((matches = issueRegex.exec(title)) !== null) {
                issues.add(parseInt(matches[1]));
                // Add PR author as assignee
                if (pr.user && pr.user.login) {
                  assignees.add(pr.user.login);
                }
              }

              // Optionally, handle more PR metadata if needed
            }

            if (issues.size === 0) {
              console.log('No issue references found.');
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            for (const issue_number of issues) {
              await addLabel(owner, repo, issue_number);
              for (const username of assignees) {
                await assignUser(owner, repo, issue_number, username);
              }
            }
