name: Run pytest

on:
  push:
    paths:
      - '**/*.py'            # All Python files in any directory
      - 'requirements.txt'  # Dependency file
      - 'setup.py'          # Setup script
      - 'pyproject.toml'    # Modern Python project configuration
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest
